# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: precheck
    jobs:
      - job: terrascan
        steps: 
          - task: DockerInstaller@0
            displayName: 'Docker installation'
            inputs:
              dockerVersion: '17.09.0-ce'         
          - task: CmdLine@2
            displayName: 'terrascan execution'
            inputs:
              script: 'docker run --rm -i -v "$(pwd):/iac" -w "/iac" tenable/terrascan scan'
      - job: tflint
        steps: 
          - task: DockerInstaller@0
            displayName: 'Docker installation'
            inputs:
              dockerVersion: '17.09.0-ce'
          - task: CmdLine@2
            displayName: 'tflint execution'
            inputs:
              script: 'docker run --rm -v $(pwd):/data -t ghcr.io/terraform-linters/tflint'
      - job: tfsec
        steps: 
          - task: DockerInstaller@0
            displayName: 'Docker installation'
            inputs:
              dockerVersion: '17.09.0-ce'        
          - task: CmdLine@2
            displayName: 'tfsec execution'
            inputs:
              script: 'docker run --rm -i -v "$(pwd):/src" aquasec/tfsec /src'
      - job: kics
        steps: 
          - task: DockerInstaller@0
            displayName: 'Docker installation'
            inputs:
              dockerVersion: '17.09.0-ce'
          - task: CmdLine@2
            displayName: 'KICS execution'
            inputs:
              script: 'docker run -v "$(pwd):/path" checkmarx/kics:latest scan -p /path -o "/path/"'
      - job: infracost
        steps:
          - task: DockerInstaller@0
            inputs:
              dockerVersion: '17.09.0-ce'
          - task: CmdLine@2
            displayName: 'infracost estimation'
            inputs:
              script: 'docker run --rm -e INFRACOST_API_KEY=ico-Zrh3mM81deTK3Tp5smYw4Ej0ycVGCqzE -v $PWD/:/code/ infracost/infracost:ci-latest breakdown --path /code/'

